import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LandingPage from '../components/LandingPage'

//API default endpoint
const defaultEndpoint =  'https://fe-assignment.vaimo.net/'


//serverSideProps to fetch data server side rendering 
export async function getServerSideProps (){
  const res = await fetch(defaultEndpoint);
  const data =await res.json();
  return{
    props:{
      data
    }
  }
}

export default function Home({data}) {
  const {results=[]}=data
  console.log('data', data)
  return (
    <div>
      <Head>
        <title>Viamo Assesment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage/>
    </div>

  )
}
